/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e7e8e9",
        "outline": "#717786",
        "error-container": "#ffdad6",
        "surface-bright": "#f8f9fa",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#26467d",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "on-error": "#ffffff",
        "inverse-surface": "#2e3132",
        "primary-fixed-dim": "#adc6ff",
        "on-tertiary-fixed": "#2f1500",
        "secondary": "#405e96",
        "surface-container-low": "#f3f4f5",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c1c6d7",
        "inverse-primary": "#adc6ff",
        "on-secondary-container": "#2d4c83",
        "on-primary-fixed-variant": "#004493",
        "secondary-fixed": "#d8e2ff",
        "tertiary": "#8d4b00",
        "secondary-fixed-dim": "#adc6ff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#d8e2ff",
        "primary": "#0058bc",
        "on-primary-fixed": "#001a41",
        "surface-variant": "#e1e3e4",
        "surface-tint": "#005bc1",
        "surface": "#f8f9fa",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#001a41",
        "tertiary-fixed-dim": "#ffb77d",
        "primary-container": "#0070eb",
        "inverse-on-surface": "#f0f1f2",
        "error": "#ba1a1a",
        "surface-dim": "#d9dadb",
        "background": "#f8f9fa",
        "on-background": "#191c1d",
        "surface-container-highest": "#e1e3e4",
        "on-surface-variant": "#414755",
        "on-tertiary-fixed-variant": "#6e3900",
        "surface-container": "#edeeef",
        "on-primary-container": "#fefcff",
        "tertiary-container": "#b15f00",
        "secondary-container": "#a1befd",
        "tertiary-fixed": "#ffdcc3",
        "on-surface": "#191c1d"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "serif": ["Noto Serif", "serif"],
        "sans": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "md": "0.375rem"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
